name: publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: npm package version (without 'v' prefix)
        required: true
        type: string
      dryRun:
        description: dry run - run the workflow without publishing to npm
        required: true
        default: true
        type: boolean

# push:
#   branches:
#     - main
#     - chore/automatic-release

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
      - run: npm install
      - run: npm run build

      - name: update package version
        run: |
          echo "updating package version to $PACKAGE_VERSION"
          npm version $PACKAGE_VERSION
        env:
          PACKAGE_VERSION: ${{ inputs.version }}

      - name: push version change
        run: git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: npm publish
        if: ${{ inputs.dryRun != true }}
        run: echo "publishing to npm $PACKAGE_VERSION"
        env:
          PACKAGE_VERSION: ${{ inputs.version }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

      # npm publish --access public

      # tag the release, using action-gh-release action
      # - uses: softprops/action-gh-release@v1
      #   with:
      #     files: dist/*.tgz
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
