name: publish

on:
  push:
    branches:
      - main
      - chore/automatic-release

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    if: ${{ startsWith(github.event.head_commit.message, 'release:') }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm install
      - run: npm run build
      - run: npm pack
      # - run: npm publish --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

      # tag the release, using action-gh-release action
      # - uses: softprops/action-gh-release@v1
      #   with:
      #     files: dist/*.tgz
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
